spring:
  application:
    name: java-db-producer
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/debezium_poc_db
    username: postgres
    password: postgres